site_name: LWC
site_favicon: favicon.ico
repo_url: https://github.com/Hidendra/LWC
theme: readthedocs

pages:
- ['index.md', 'Home']
- ['whats-new.md', 'What''s New?']
- ['migration/differences.md', 'Migrating from LWC v4', 'Differences']
- ['user-guide/installation.md', 'User Guide', 'Installation']
- ['user-guide/commands.md', 'User Guide', 'Commands']
- ['user-guide/permissions.md', 'User Guide', 'Permissions']
- ['user-guide/translations.md', 'User Guide', 'Translations']
- ['plugin-integration/index.md', 'Plugin Integration', 'Plugin Integration']
- ['about/license.md', 'About', 'License']
- ['about/release-notes.md', 'About', 'Release Notes']


