# In development config file for LWC 5.0.0
# This should not be used on production servers

core:

    # The default language to use for players and the console.
    locale: en_US

protections:
    protectables:
        chest:
            enabled: true
        furnace:
            enabled: true

# database connection details
database:

    # the db driver
    driver: h2

    # The path to the database if required (for SQLite, not MySQL)
    databasePath: '%home%/lwc.db'

    # the database server's hostname
    hostname: '127.0.0.1'

    # the database name to use (if appropriate)
    database: lwc

    # username to connect as
    username: root

    # password to connect with
    password: ''

    # the table prefix
    prefix: ''